website/views.py
from pathlib import Path
from .common import get_website_dir
from flask import Blueprint, flash, jsonify, render_template, \
                  request, send_file, session
import json
import requests
from .kb_graph import graph, n, add_triple, generator_to_list, \
                     isolate_last_part_of_URI, input_new_triple, \
                     string_to_URI, triple_to_text, \
                     text_to_triple, save_graph

views = Blueprint('views', __name__)


def get_subjects(topic, relation, target=None):
    """ Get all the subjects of a relation for the given object. """  
    subs = graph.triples((None, relation, string_to_URI(topic)))
    return [isolate_last_part_of_URI(a[0]).replace("_", " ") for a in subs]

def get_attributes(topic, relation):
    atts = graph.triples((string_to_URI(topic), relation, None))
    return [isolate_last_part_of_URI(a[2]).replace("_", " ") for a in atts]


@views.route('/')
def home():

    methods_t = graph.triples((None, n.is_a, n.method))
    methods = [isolate_last_part_of_URI(m[0]) for m in methods_t]
    methods.sort() 

    apps_t = graph.triples((None, n.is_a, n.application))
    applications = [isolate_last_part_of_URI(a[0]) for a in apps_t]
    applications.sort() 

    return render_template('home.html', methods=methods,
                                        applications=applications)



@views.route('/topic/<string:topic>')
def topic(topic):

    # Title
    title = topic.replace("_", " ").title()
    print("Title:", title)


    # Description
    description = get_attributes(topic, n.description)
    print("Description:", description)

    # What it is - "is a"
    is_a_items = get_attributes(topic, n.is_a)
    print("Is a:", is_a_items)

    # Definition - "definition" 
    definitions = get_attributes(topic, n.definition)
    print("Definitions:", definitions)
    
    # Applications - "can do" - <object>
    # If the topic is a [method], list the applications it can do.
    applications = get_attributes(topic, n.can_do)
    print("Applications:", applications)

    # Methods - "can do" - <subject>
    methods = get_subjects(topic, n.can_do)
    print("Methods:", methods)

    # Advantages - "has advantage"
    advantages = get_attributes(topic, n.has_advantage)
    print("Advantages:", advantages)

    # Disadvantages - "has disadvantage"
    disadvantages = get_attributes(topic, n.has_disadvantage)
    print("Disdvantages:", disadvantages)

    # Examples - "example"
    examples = get_attributes(topic, n.example)
    print("Examples:", examples)


    return render_template("topic.html", 
                           description=description,
                           topic=topic, 
                           title=title,
                           is_a_items=is_a_items,
                           definitions=definitions,
                           applications=applications,
                           methods=methods,
                           advantages=advantages,
                           disadvantages=disadvantages,
                           examples=examples)


@views.route('/examples/<string:example>')
def example_page(example):
    return render_template("/examples/{}.html".format(example))


@views.route('/knowledge-base', methods=['GET', 'POST'])
def knowledge_base():
    """ 
    Knowledge Base page

    - See all the triples in the knowledge base
    - Manually add and remove triples 
    - Save the knowledge base to file "graph.n3"
    """
    # When "Enter" button is pressed:
    if request.method == 'POST':

        # Get user input from subject, predicate, and object fields
        subject = request.form.get("subject")
        predicate = request.form.get("predicate")
        obj = request.form.get("object")

        # Validate input
        if len(subject) == 0 or len(predicate) == 0 or len(obj) == 0:
            flash("Must enter a value in all three fields.", category="error")
        else:

            # Convert to RDF triple format
            s, p, o = input_new_triple(subject, predicate, obj)

            # Check if triple is already in the graph
            if (s, p, o) in graph:
                flash("Triple already exists", category="error")
            else:

                # Add the triple to the graph
                add_triple(s, p, o)
                print("\nJust added:\n", subject, " - ", predicate, " - ", obj,
                      "\nIn RDF format: ", s, p, o)

    # Load all the triples from the graph into a list, convert them into plain text, and sort them
    triples = []
    for s, p, o in graph:
        triples.append((s, p, o))
    triples.sort()
    triples_text = [triple_to_text(t) for t in triples]

    # Pass all the triples to the template to be displayed
    return render_template('knowledge-base.html', triples_text=triples_text)


@views.route('/download/<path:filepath>', methods=['GET', 'POST'])
def download(filepath):
    path = Path(get_website_dir()) / filepath
    return send_file(path, as_attachment=True)


@views.route('/recommender', methods=['GET', 'POST'])
def recommender():
    """ 
    Machine Learning Tool Recommender page

    - Select an application from the drop down menu
    - View the results that match the query ( ? , can do , [selected application] )
    """
    # Get all the applications to be listed in the drop down menu
    application_triples = graph.triples((None, n.is_a, n.application))
    applications = [isolate_last_part_of_URI(a[0]).replace("_", " ") for a in application_triples]
    applications.sort() 

    # Initialize defaults
    default_application_text = "e.g., 'image generation'"  # Placeholder in drop down menu
    selected_application = default_application_text        # Selection in drop down menu
    data = dict()                                          # Holds the results of the query

    # When "Get Recommendation" button is pressed:
    if request.method == 'POST':

        # Get the selected application from the drop down menu
        selected_application = request.form.get("applicationSelect")

        # Get all the methods that can do the selected application
        results = graph.triples((None, n.can_do, string_to_URI(selected_application)))
        relevant_methods = [r[0] for r in results]
        relevant_methods.sort()

        # For each method, get its:
        #  - name,
        #  - description, 
        #  - advantages,
        #  - disadvantages, and
        #  - links
        for method in relevant_methods:
            data[method] = dict()

            data[method]["name"] = isolate_last_part_of_URI(method).replace("_", " ").capitalize()

            data[method]["description"] = isolate_last_part_of_URI(graph.value(method, n.description))

            advantages = graph.triples((method, n.has_advantage, None))
            data[method]["advantages"] = [isolate_last_part_of_URI(a[2]).replace("_", " ") for a in advantages]

            disadvantages = graph.triples((method, n.has_disadvantage, None))
            data[method]["disadvantages"] = [isolate_last_part_of_URI(d[2]).replace("_", " ") for d in disadvantages]

            links = graph.triples((method, n.link, None))
            data[method]["links"] = [isolate_last_part_of_URI(l[2]) for l in links]

    # Pass the applications and the results (if any) to the recommender template to be displayed
    return render_template('recommender.html', default_application_text=default_application_text,
                                               applications=applications,
                                               selected_application=selected_application,
                                               data=data)


@views.route('/query', methods=['GET', 'POST'])
def query():
    """
    Custom Queries page

    - Choose any combination of subject, predicate, or object from the dropdown menu
    - Select '?' to act as a wildcard value
    - View all the triples that satisfy the query
    """
    # Gather all the unique subjects, predicates, and objects to be listed in their corresponding drop down menus
    subjects = generator_to_list(graph.subjects())
    predicates = generator_to_list(graph.predicates())
    objects = generator_to_list(graph.objects(), exclude_literals=True)

    # By default, set selection fields to the wildcard value
    wildcard_text = '?'
    selected_subject = wildcard_text
    selected_predicate = wildcard_text
    selected_obj = wildcard_text

    results_text = []

    # When "Submit" button is pressed:
    if request.method == 'POST':

        # Get the values from the drop down menus
        selected_subject = request.form.get('subjectSelect')
        selected_predicate = request.form.get('predicateSelect')
        selected_obj = request.form.get('objectSelect')

        # Convert the input into the necessary format, setting wildcards to None
        q_text = [selected_subject, selected_predicate, selected_obj]
        q = [None, None, None]
        for i in range(3):
            # For each of the three values (subject, predicate, object), if the selected
            #  value is not the wildcard value, convert it into a URI and replace the
            #  None placeholder in query q
            if q_text[i] != wildcard_text:
                q[i] = string_to_URI(q_text[i])

        # Query the knowledge base and convert the results to plain text in a sorted list
        results = graph.triples(tuple(q))
        results_text = [triple_to_text(t) for t in results]
        results_text.sort()

    # Pass all the values and results (if any) to the query template to be displayed
    return render_template('query.html', selected_subject=selected_subject,
                                         selected_predicate=selected_predicate,
                                         selected_obj=selected_obj,
                                         subjects=subjects, 
                                         predicates=predicates,

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">


        <!-- Bootstrap imports -->

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" 
              rel="stylesheet" 
              integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" 
              crossorigin="anonymous">

        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
            integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
            crossorigin="anonymous"
        />
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
            crossorigin="anonymous"
        />



        <title>{% block title %}AIKB{% endblock %}</title>
    
    </head>

    <body style="background-color:rgb(235, 240, 245)"></body>
        

        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button
                class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbar"
            >
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                <div class="navbar-nav">
                        <a class="nav-item nav-link" id="home" href="/">Home</a>
                        <a class="nav-item nav-link" id="knowledge-base" href="/knowledge-base">Knowledge Base</a>
                        <a class="nav-item nav-link" id="recommender" href="/recommender">Recommender</a>
                        <a class="nav-item nav-link" id="query" href="/query">Custom Query</a>
                        <a class="nav-item nav-link" id="query-rag" href="/query-rag">Ask Chatbot</a>
                </div>
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %} 
                {% for category, message in messages %}
                    {% if category == "error" %} 

                    <div class="alert alert-danger alter-dismissable fade show" role="alert">
                        {{ message }} 
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times</span>
                        </button>
                    </div>

                    {% else %}

                    <div class="alert alert-success alter-dismissable fade show" role="alert">
                        {{ message }} 
                        <button type="button" class="close" data-dismiss="alert">
                            <span aria-hidden="true">&times</span>
                        </button>
                    </div>
                    
                    {% endif %} 
                {% endfor %}
            {% endif %} 
        {% endwith %}

        <br />
            {% block heading %} {% endblock %}
        <br />

        <div class="container">
            {% block content %} {% endblock %}
        </div>

        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js"
                integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" 
                crossorigin="anonymous"
        ></script>

        <script
            src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
            integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"
        ></script>

        <script
            type="text/javascript"
            src="{{ url_for('static', filename='index.js') }}"
        ></script>


    </body>
</html>

website/templates/content_page.html
{% block heading %}
<h1 align='center'>James' Machine Learning Knowledge Base</h1>
<h4 align='center'>by James Butcher - Version 1.0, March 2021</h4>
{% endblock %}

{% block content %}


<h1>{{ content_page.title }}</h1>
    {{ content_page.content | safe }}
    {{ content_page.code_snippet }}
    {% for link in links %}
        <p>Related topic: <a href="{{ url_for('topic', topic_id=link.source_topic_id) }}">{{ link.source_topic.name }}</a></p>
    {% endfor %}


{% endblock %}

website/templates/home.html
{% extends "base.html" %}

{% block heading %}
<h2 align='center'>AI Knowledge Base</h2>
<h4 align='center'>James Butcher - Version 2.0, 2024</h4>
{% endblock %}

{% block content %}




<div class="container-sm">

    <div class="row">

        <div class="col-sm">

            <h1>Methods</h1>
            <ul>
                
                {% for method in methods %}
                    <li><a href="{{ url_for('views.topic', topic=method) }}">{{ method.replace("_", " ").title() }}</a></li>
                {% endfor %}
                
            </ul>

        </div>

        <div class="col-sm">

            <h1>Applications</h1>
            <ul>
                
                {% for application in applications %}
                    <li><a href="{{ url_for('views.topic', topic=application) }}">{{ application.replace("_", " ").title() }}</a></li>
                {% endfor %}
                
            </ul>

        </div>

    </div>

</div>




<div class="container-sm">




<!--
<h1>Index</h1>
<ul>
    
    {% for topic in topics %}
        <li><a href="{{ url_for('views.topic', topic=topic) }}">{{ topic.replace("_", " ").title() }}</a></li>
    {% endfor %}
    
</ul>
-->

<h4>Introduction</h4>

    <p>Welcome to my base of AI/ML knowledge!</p>

    <p>One of the goals of this project is to help AI and Machine Learning
    engineers choose the right tools for a given problem. There are so many
    out there that it is easy to get lost.
    </p>

    <p>This knowledge base contains all kinds of information about machine
    learning methods and how they compare. It describes which methods can be
    used for certain applications as well as their advantages and disadvantages.
    </p>
    
    <p>The knowledge embodied as an RDF graph, a semantic web technology 
    consisting of many interconnected "things" called <i>resources</i>.
    These resources can be <b>concepts</b> such as <i>linear regression</i> or 
    <b>properties</b> such as <i>has advantage</i> or  <b>literals</b> such as
    <i>"very simple."</i>
    </p>
    
    <p>These connections are represented as <b>triples</b> consisting of a
    <b>subject</b>, a <b>predicate</b>, and an <b>object</b>.
    </p>

    <img src="static/triples_diagram1.png" class="img-fluid" alt="triples diagram">

    <p>The above diagram depicts two triples: (classification, is a, application)
    and (decision tree, can do, application). Note that the resource called 
    "classification" appears twice. In an RDF graph, these two instances of 
    "classification" refer to the same thing. 
    Thus, a list of triples together builds a sort of "web" of knowledge.
    This is the backbone of the knowledge graph structure. Below is a small 
    example of what such a knowledge graph looks like:
    </p>
    
    <img src="static/simple_graph1.png" class="img-fluid" alt="simple graph">

    <p>This framework is extremely flexible. You can use any concept or 
    property you wish to express relationships in any domain of knowledge.
    For example, the above diagram can be extended by adding triples
    representing subclass relationships. One of these could be:
    (logistic regression, subclass of, supervised learning).
    </p>

    <p>Or, as I found very useful, triples representing the strengths and
    weaknesses of various machine learning methods. For example:
    (decision tree, has advantage, "creates good explanations"), and 
    (decision tree, has disadvantage, "only easily interpretable when short").
    This comes in handy when comparing different methods to use for a given
    application.
    </p>

    <br />

    <a href="/knowledge-base"><h4>Add/Remove Triples from Knowledge Base</h4></a>

    <p>The "Knowledge Base" page lists all the triples currently in the knowledge
     base.
    </p>

    <p><b>To add a triple:</b> Enter a subject, a predicate, and an object in 
    the corresponding input fields and click enter. Be sure to use consistent
    spelling when entering multiple triples containing the same thing. All
    inputs are case-sensitive.
    </p>

    <p><b>To delete a triple:</b> Simply scroll down to the triple you want to
    delete and click the 'X' on the right.
    </p>

    <p>Be sure to click "Save" if you want to save your changes to the graph file.
    </p>

    <br />

    <a href="/recommender"><h4>Recommender Tool</h4></a>

    <p>The "Recommender" page lets you select the application you are interested
    in and then generates a neat list of relevant machine learning methods and
    information about each one, including their advantages and disadvantages. 
    </p>

    <p>It does this by querying the knowledge base for all subjects that meet
    the criteria: [subject] --> can do --> [selected application], and then
    gathers all other information on that subject.
    </p>

    <br />

    <a href="/query"><h4>Custom Queries</h4></a>

    <p>The "Custom Query" page lets you examine the knowledge base in more detail.
    </p>

    <p>Select the subject, predicate, or object you are interested in while
    leaving the other fields with the default '?' selection acting as a wildcard,
    and the program will fetch all the triples that meet the criteria.
    </p>

    <p>For example, if you wanted to see all of the different applications in
    the knowledge base, you would select '?' for the subject, "is a" for the
    predicate, and "application" for the object. Similarly, if  you wanted
    to see all of the things k-means clustering can do, you would select
    "k-means clustering" for  the subject, "can do" for the predicate, and '?'
    for the object.
    </p>

    <br />
    <br />

    <hr>

    <p>&copy; <i>James Butcher 2024 - jmsbutcher1567@gmail.com</i></p>
    
</div>

{% endblock %}

website/templates/knowledge-base.html
{% extends "base.html" %}

{% block heading %}<h2 align="center">Knowledge Base</h2>{% endblock %}

{% block content %}

<h3>Add triples</h3>

<form method="POST">
    <div class="row mb-3">
        <label for="subject" class="col-sm-2 col-form-label">Subject:</label>
        <div class="col-sm-10">
            <input type="text"
                class="form-control"
                id="subject"
                name="subject"
                placeholder="Enter a subject (e.g., regression .. )"/>
        </div>
    </div>
    <div class="row mb-3">
        <label for="predicate" class="col-sm-2 col-form-label">Predicate:</label>
        <div class="col-sm-10">
            <input type="text"
                class="form-control"
                id="predicate"
                name="predicate"
                placeholder="Enter a predicate (e.g., .. is a .. )"/>
        </div>
    </div>
    <div class="row mb-3">
        <label for="object" class="col-sm-2 col-form-label">Object:</label>
        <div class="col-sm-10">
            <input type="text"
                class="form-control"
                id="object"
                name="object"
                placeholder="Enter an object (e.g., .. method )"
                aria-describedby="objectInputHelp"/>
            <div id="objectInputHelp" class="form-text">
                - Enclose long text in quotes ("...") to store as a literal instead of a URI.
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Enter</button>
</form>

<br />
<br />

<h3>Triples</h3>

<div class="d-grid gap-2 col-6 mx-auto">
    <button type="button" class="btn btn-primary" onClick="saveGraph()">Save</button>
</div>

<ul class="list-group list-group-flush" id="triples">
    {% for triple in triples_text %}
        <li class="list-group-item">{{ triple }}
            <button type="button" class="close" onClick="deleteTriple('{{ triple }}')">
                <span aria-hidden="true">&times;</span>
            </button>
        </li>
    {% endfor %}
</ul>


<a href="{{ url_for('views.download', filepath='graph.n3') }}">Download graph</a>


{% endblock %}

website/templates/query-rag.html
{% extends "base.html" %}

{% block heading %}<h2 align='center'>Ask Knowledge Base Chatbot</h2>{% endblock %}

{% block content %}

<form method="POST">
    <div class="row mb-3">
        <label for="question" class="col-sm-2 col-form-label">Question:</label>
        <div class="col-sm-10">
            <input type="text"
                class="form-control"
                id="question"
                name="question"
                placeholder="Enter your question"
                aria-describedby="questionInputHelp"/>
            <div id="questionInputHelp" class="form-text">
                (e.g., What are the pros and cons of decision trees?)
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary">Enter</button>
</form>

<br/>

<div class="container">
    <h4>Answer:</h4>
    <p>{{ answer }}</p>
</div>

{% endblock %}

website/templates/query.html
{% extends "base.html" %}

{% block heading %}<h2 align='center'>Custom Queries</h2>{% endblock %}

{% block content %}

<form method="POST">
    <div class="form-group">
        <h3>Select from knowledge base:</h3>
        <div class="input-group mb-3">
            <label class="input-group-text" for="subjectSelect">Subject</label>
            <select class="form-select" id="subjectSelect" name="subjectSelect">
            <option selected>{{ selected_subject }}</option>
            {% if selected_subject != wildcard_text %}
                <option value='{{ wildcard_text }}'>{{ wildcard_text }}</option>
            {% endif %}
            {% for subject in subjects %}
                <option value='{{ subject }}'>{{ subject }}</option>
            {% endfor %}
            </select>
        </div>
        <div class="input-group mb-3">
            <label class="input-group-text" for="predicateSelect">Predicate</label>
            <select class="form-select" id="predicateSelect" name="predicateSelect">
            <option selected>{{ selected_predicate }}</option>
            {% if selected_predicate != wildcard_text %}
                <option value='{{ wildcard_text }}'>{{ wildcard_text }}</option>
            {% endif %}
            {% for predicate in predicates %}
                <option value='{{ predicate }}'>{{ predicate }}</option>
            {% endfor %}
            </select>
        </div>
        <div class="input-group mb-3">
            <label class="input-group-text" for="objectSelect">Object</label>
            <select class="form-select" id="objectSelect" name="objectSelect">
            <option selected>{{ selected_obj }}</option>
            {% if selected_obj != wildcard_text %}
                <option value='{{ wildcard_text }}'>{{ wildcard_text }}</option>
            {% endif %}
            {% for object in objects %}
                <option value='{{ object }}'>{{ object }}</option>
            {% endfor %}
            </select>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

<div class="container">
    <h4 align="center">Results</h4>
    {% for result in results_text %}
        <p>{{ result }}</p>
    {% endfor %}
</div>

{% endblock %}

website/templates/recommender.html
{% extends "base.html" %}

{% block heading %}<h2 align='center'>Machine Learning Tool Recommender</h2>{% endblock %}

{% block content %}

<form method="POST">
    <div class="form-group">
        <h3>What is the application?</h3>
        <div class="input-group mb-3">
            <label class="input-group-text" for="applicationSelect">Application Type</label>
            <select class="form-select" id="applicationSelect" name="applicationSelect">
            <option selected>{{ selected_application }}</option>
            {% if selected_application != default_application_text %}
                <option value='{{ default_application_text }}'>{{ default_application_text }}</option>
            {% endif %}
            {% for application in applications %}
                <option value='{{ application }}'>{{ application }}</option>
            {% endfor %}
            </select>
        </div>

        <br />
        <button type="submit" class="btn btn-primary">Get Recommendation</button>

    </div>
</form>

<hr>

{% for method in data.keys() %}
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">{{ data[method]["name"] }}</h5>
            
            <h6 class="card-subtitle mb-2">Advantages:</h6>
            <ul>
            {% for advantage in data[method]["advantages"] %} 
                <li>{{ advantage }}</li>
            {% endfor %}
            </ul>

            <h6 class="card-subtitle mb-2">Disdvantages:</h6>
            <ul>
            {% for disadvantage in data[method]["disadvantages"] %} 
                <li>{{ disadvantage }}</li>
            {% endfor %}
            </ul>

            <h6 class="card-subtitle mb-2">Description:</h6>
            <p class="card-text">{{ data[method]["description"] }}</p>

            <h6 class="card-subtitle mb-2">Learn More:</h6>
            {% for link in data[method]["links"] %} 
                </p><a href="{{ link }}" class="card-link" target="_blank">{{ link }}</a>
            {% endfor %}
        </div>
    </div>
  {% endfor %}

{% endblock %}

website/templates/topic.html
{% extends "base.html" %}


{% block title %}{{ topic }}{% endblock %}


{% block heading %}
<h2 align='center'>{{ title }}</h2>
{% endblock %}


{% block content %}

<!-- Description -->
{% if description|length > 0 %}
<ul>
    {% for d in description %}

        <li>{{ d }}</li>

    {% endfor %}
    </ul>
{% endif %}

<!-- "Is a" -->
{% if is_a_items|length > 0 %}
    <h3>Is a:</h3>
    <ul>
    {% for is_a in is_a_items %}

        <li>{{ is_a }}</li>

    {% endfor %}
    </ul>
{% endif %}

<!-- Definition -->
{% if definitions|length > 0 %}
    <h3>Definition:</h3>
    <ul>
    {% for definition in definitions %}

        <li>{{ definition }}</li>

    {% endfor %}
    </ul>
{% endif %}

<!-- Applications -->
{% if applications|length > 0 %}
    <h3>Applications:</h3>
    <ul>
        {% for application in applications %}
        
            <li><a href="{{ url_for('views.topic', topic=application) }}">{{ application.title() }}</a></li>
        
        {% endfor %}
    </ul>
{% endif %}

<!-- Methods -->
{% if methods|length > 0 %}
    <h3>Methods:</h3>
    <ul>
        {% for method in methods %}
        
            <li><a href="{{ url_for('views.topic', topic=method) }}">{{ method.title() }}</a></li>
        
        {% endfor %}
    </ul>
{% endif %}


<!-- Advantages -->
{% if advantages|length > 0 %}
    <h3>Advantages:</h3>
    <ul>
        {% for advantage in advantages %}
        
            <li>{{ advantage }}</li>
        
        {% endfor %}
    </ul>
{% endif %}

<!-- Disadvantages -->
{% if disadvantages|length > 0 %}
    <h3>Disadvantages:</h3>
    <ul>
        {% for disadvantage in disadvantages %}
        
            <li>{{ disadvantage }}</li>
        
        {% endfor %}
    </ul>
{% endif %}

<!-- Examples -->
{% if examples|length > 0 %}
    <h3>Examples:</h3>
    <ul>
        {% for example in examples %}
        
        <li><a href="{{ url_for('views.example_page', example=example) }}" target="_blank">{{ example }}</a></li>
        
        {% endfor %}
    </ul>
{% endif %}


{% endblock %}